  language: scala

  jdk:
    - oraclejdk8

  script:
    - "./ci/run-tests.sh"

  addons:
    postgresql: "9.3"

  before_script:
    - psql -c "create database steel_test;" -U postgres
    - psql -c "create user steel_test with password 'test';" -U postgres
    - psql -c "grant all privileges on database steel_test to steel_test;" -U postgres

  repo_token: Rgd35INMOfKzKZUql721cR6TFD7hiDDvP

  after_script:
    - if [[ $TRAVIS_TEST_RESULT == 0 && "$TRAVIS_BRANCH" == "master" ]]; then sbt "^publish"; fi
